### ISSUE TITLE
Wiki and hero editing side by side

### ISSUE THREAD

**Issue by Elytherion** [Elytherion/tdeheroes#10]
All texts from the German Regel-Wiki (and respective translations) made available offline next to entries in hero view lists.

- [x] Spell Extensions (texts)
- [x] Spell Extensions (implementation)
- [x] Liturgical Chant Extensions (texts)
- [x] Liturgical Chant Extensions (implementation)
- [x] Professions (texts)
- [x] Professions (implementation)
- [x] Profession Variants (texts)
- [x] Profession Variants (implementation)
- [x] Advantages (texts)
- [x] Advantages (implementation)
- [x] Disadvantages (texts)
- [x] Disadvantages (implementation)
- [x] Special Abilities (texts)
- [x] Special Abilities (implementation)
- [x] Combat Techniques (texts)
- [x] Combat Techniques (implementation)
- [x] Items (texts)
- [x] Items (implementation)

**Comment by Elytherion** [comment]
Texts for Skills complete and available in the next update!

**Comment by theShmoo** [comment]
Maybe this helps? 
https://github.com/theShmoo/DSA5SpellBook/blob/master/app/components/data.js

**Comment by Elytherion** [comment]
Actually, I am almost done with the spell descriptions. The spell effects texts are the only ones that are not complete. And I need Markdown syntax or visible font style changes for adding Markdown so that I can display them inside the app.

EDIT: I can copy/paste it and then add the MD tags manually ... Thanks! :)

P.S.: Did you create files for liturgical chants as well? ^^

**Comment by theShmoo** [comment]
I did plan to create something similar as the dsa5spellbook for the liturgies. I could parse the liturgies from the wiki if you want to. 

But if you don't want all the text (for now) from the descriptions you can use the javascript files from the self calculating document (pdf) these contain all properties of everything you need (e.g.: Weapon lists, ....) If you don't have a pdf reader that can access the js files I can send them to you.

**Comment by Elytherion** [comment]
That would be awesome, cause it's easier to do it with your JSON as with the Rules Wiki itself. Can you tell me how much time you would need to generate the JSON file?

Actually, the texts are the only thing missing. All the other stuff is already done, as I need it for calculating everything. So your JSON file(s) would be the only ones needed to complete my tables.

Thank you in advance!!! :)

**Comment by theShmoo** [comment]
Ok I will try to send it to you asap. 

This weekend should be possible.

**Comment by Elytherion** [comment]
Awesome, thank you so much!!!!!!!

**Comment by theShmoo** [comment]
Hello!

Sadly I have less time than expected. Here are the scraped liturgies:
https://gist.github.com/theShmoo/420f8b48aebba0cde2c3754dd31f96e2
The extensions are not properly parsed but the "wirkung" should be there

If you need any other scraped data from the wiki. Just ask! I wrote this little scrapy project that helps me getting the data:
https://github.com/theShmoo/DSA5RegelWikiParser

**Comment by Elytherion** [comment]
Again: Thank you so much!!! :)

**Comment by Elytherion** [comment]
Text for spells done. Once the texts for liturgical chants are done, too, I expect to be able to release a new update!

**Comment by Elytherion** [comment]
Texts for blessings and cantrips done, liturgical chants WIP.

**Comment by Elytherion** [comment]
Liturgical chants done.

**Comment by Elytherion** [comment]
Cultures done (except for language specializations which are not a feature of the app yet).

**Comment by Elytherion** [comment]
Just a little list for myself to keep track of the missing parts (in German):

- Spell Extensions (implementation only)
- Liturgical Chant Extensions (texts and implementation)
- Professions
- Profession Variants
- Advantages
- Disadvantages
- Special Abilities
- Items

**Comment by theShmoo** [comment]
Hello,
Wolf Weidner published a project on the scriptorium, and removed it shortly after again. 
I was able to download it. It contains the browsable html data from the wiki.
You can find it here: https://www.pfahler.at/regelref/ you could use its json data for your application.

Cheers.

**Comment by Elytherion** [comment]
Actually pretty cool, but sadly advantages, disadvantages and special abilities are almost done, so this would not really help anymore. :( Thank you, anyway!! :)

**Comment by Elytherion** [comment]
Advantages, disadvantages and special abilities done except for the prerequisites.
