### ISSUE TITLE
Auto Updater Error Message

### ISSUE THREAD

**Issue by mfxbe** [Elytherion/tdeheroes#100]
According to #85 there is no auto updater for Linux but I still get a message (see image, would be useful to make this messages _copy-able_) that a error occurred. If it's possible I would recommend to completely disable the updater for Linux to just get rid of this message.

![bildschirmfoto von 2017-11-29 12-23-39](https://user-images.githubusercontent.com/10778257/33372995-4e387680-d500-11e7-816c-f9e30b43de90.png)

**Comment by Elytherion** [comment]
I will disable it and I will add a button to copy the text to the clipboard. Thanks! :)
