### ISSUE TITLE
Additional update infos (A few nice-to-have things)

### ISSUE THREAD

**Issue by Stemw3** [Elytherion/tdeheroes#104]
A few things that would be really neat to have at the update-screens.
-The size of the update at the screen where you can choose to download the update.
-A progress indicator in percent and actual downloaded size as well as the download speed above the progress bar. Something like: "25MB/50MB (50%) downloaded. Download Speed: 1.5MB/s"

**Comment by Elytherion** [comment]
I'm not sure if I can add this to the 1.0, but I will implement this in the nearer future!! :)

**Comment by Elytherion** [comment]
Sadly, I cannot display the download size in the dialog where you can choose to update - the used library does not support this. But I added infos to the process dialog!
