### ISSUE TITLE
Wrong prerequisites for the special ability 'Roll over' (Abrollen)

### ISSUE THREAD

**Issue by Tengwean** [Elytherion/tdeheroes#114]
In the german version of the app (0.51.8), one of the prerequisites is _Body Control 8_ whereas in the Aventurian Compendium and in the TDE Game Reference only _Body Control 4_ is required.

**Comment by Elytherion** [comment]
Probably a (very old!!!!) copy/paste issue. Anyway: Fixed! Thanks!
