### ISSUE TITLE
Problems when calculating the AP "Skill Specialization (Skill)"

### ISSUE THREAD

**Issue by Tengwean** [Elytherion/tdeheroes#115]
Just happened with _Gods & Cults_ and with _Alchemy_. Added them and removed them multiple times. At some point the costs were of: the ability would cost more (i.e. fist Secialization on Alchemy would cost 12 AP istead of 3) and would only refund 3 (the expected value).

**Comment by Elytherion** [comment]
Did you add/remove multiple specializations for a specifc skill at once or did you add/remove only one skill application at once?

**Comment by Tengwean** [comment]
It happens when first adding at least two specializations for one skill, then removing and afterwards adding them again. Just tried again with _Stealth_ I added the two specializations and everything was calculated right and there was no problem either when removing them. But when I wanted to add it again, it was calculated to cost 48 AP.
I did not have any problems when just adding one specialization per skill.

**Comment by Elytherion** [comment]
Dumb issue...
