### ISSUE TITLE
When exported to PDF, the menu bar and scrollbar are also exported to PDF

### ISSUE THREAD

**Issue by iSneeze** [Elytherion/tdeheroes#130]
Bug Description:
The PDF export also does include scrollbars and menu bar not relevant to the actual document, as can be seen [here](https://i.imgur.com/mg7CPzb.png) and [here](https://i.imgur.com/NVEOZ2W.png)

the preview however, doesn't show this and works as [intended](https://i.imgur.com/mSmVVKy.png).

OS: Windows
Version: 0.51.9.0
Language: DE

Thank you very much for your efforts to develop and support this project! I really appreciate it.

**Comment by Elytherion** [comment]
Thanks for contributing by giving me feedback/bug reports! Otherwise I would not have found this bug.
