### ISSUE TITLE
Issue with the "Show activated"-option in the "Liturgical Chants"-Tab

### ISSUE THREAD

**Issue by Tengwean** [Elytherion/tdeheroes#132]
The standard view you have is as if you had activated the option "Show activated", if you do activate it the entries are doubled and if you then deactivate it, some entries stay doubled (or trippled, if done more than ones).

OS: Windows 10
Version: 0.51.9, german
Tested with a "Blessed one of Aves"

![bug1 1](https://user-images.githubusercontent.com/34599078/34652124-5c130bb4-f3da-11e7-8bca-55c803344836.PNG)
![bug1 2](https://user-images.githubusercontent.com/34599078/34652125-5c357d5c-f3da-11e7-9896-1f056d62bbe2.PNG)
![bug1 3](https://user-images.githubusercontent.com/34599078/34652126-5c4ede78-f3da-11e7-9aeb-016eb6908033.PNG)

**Comment by Elytherion** [comment]
Stupid mistake. Anyway, it is fixed. Thanks! ;)
