### ISSUE TITLE
Fertigstellen button funktioniert nicht

### ISSUE THREAD

**Issue by pfeifferleander** [Elytherion/tdeheroes#133]
Bei mir auf MacOs bleibt der Fertigstellen Button von der Sprachenauswahl immer Deaktiviert und nicht drückbar

**Comment by Elytherion** [comment]
Hast du auch alle anderen Auswahlfelder verwendet? Also einen Bonus für die Spezies ausgewählt etc.? Wenn ja, vielleicht einmal in die [Console](https://github.com/Elytherion/tdeheroes/blob/master/CONTRIBUTING.md) schauen, ob da Fehlermeldungen stehen.
