### ISSUE TITLE
Heldenbogen Menü im Pdf

### ISSUE THREAD

**Issue by Hokar321** [Elytherion/tdeheroes#135]
TDE5 Heroies Client V0.51.9

Das im Menüpunkt Heldenbogen->als Pdf speichern erzeugte PDF enthällt zusätzliche Elemente aus dem Benutzerinterface.
Auf der Ersten Seite sind folgende Menü Punkte aufgeführt.
![image](https://user-images.githubusercontent.com/36736881/36545494-4a9a1fa2-17e9-11e8-81ac-4b9b3413ffdf.png)
Außerdem enthält das Dokument Scrollbars Rechts und unten.
![image](https://user-images.githubusercontent.com/36736881/36545564-7bb52258-17e9-11e8-8e05-15ac2450cec1.png)

**Comment by Elytherion** [comment]
Dieser Fehler wurde leider schon gemeldet und wurde auch behoben. Trotzdem aber danke!

Duplicate of #130
