### ISSUE TITLE
AP-Fehler bei mehreren Verpflichtungsstufen

### ISSUE THREAD

**Issue by Problembeloeser** [Elytherion/tdeheroes#136]
Wenn man z.B. eine Verpflichtung I und eine Verpflichtung II hat, erhält man für die 2. Stufe 10 AP aufgrund der Differenz (was so sein soll), allerdings erhält man dann keine Punkte für die darunterliegende Stufe

**Comment by Elytherion** [comment]
Was genau meinst du? Gibt Verpfl. II 10 AP und Verpfl. I 0 AP?

**Comment by Problembeloeser** [comment]
Exakt, ich kann dir später noch einen Screenshot senden.

**Comment by Problembeloeser** [comment]
![test1](https://user-images.githubusercontent.com/36821649/36656805-2d32ed52-1aca-11e8-9139-69a5ab16a53f.png)
![test2](https://user-images.githubusercontent.com/36821649/36656807-2e95c1f6-1aca-11e8-87e7-e42a0b4a3e27.png)
Hier sieht man, was ich meine, es fehlen 10 AP in der Berechnung.
