### ISSUE TITLE
Es werden 2 Kampfblätter im Heldenbögen angezeigt

### ISSUE THREAD

**Issue by theShmoo** [Elytherion/tdeheroes#145]

**Comment by Elytherion** [comment]
Das ist richtig, es soll auch so sein. Ist wie beim Selbstrechnenden Heldenbogen: Ein Bogen für Gesamt-RS und ein Bogen für Zonen-RS. Wird besser bei einer Überarbeitung des Heldenbogens gelöst werden.

**Comment by theShmoo** [comment]
Ok passt kenne mich aus! Danke für deine tolle Arbeit 🥇👍

**Comment by Elytherion** [comment]
Danke, dass sie dir gefällt! :3
