### ISSUE TITLE
GUI bricht bei Sonderfertigkeiten ohne Voraussetzungen

### ISSUE THREAD

**Issue by Nafetsky** [Elytherion/tdeheroes#149]
Also es ist ein Bug, aber ich gebe gerne zu, dass der nur durch unsachgemäße Verwendung auftritt (oder durch Alterung, wenn das mal implementiert würde^^).
Also wenn die Reaktion ist "Das Repariere ich nicht, das bist ja selbst schuld" ist das durchaus eine verständliche Reaktion.

der technische Teil kommt weiter unten:

Wir sind von DSA 4.1 auf 5 gewechselt, weshalb einige der konvertierten Charakere Sonderfertigkeiten haben, für die sie in DSA 5 die Vorausetzungen nicht mehr erfüllen. Nun [#41](https://github.com/Elytherion/tdeheroes/issues/41) wäre wohl auch eine Lösung für uns, aber das gibt es ja noch nicht. Also war mein Vorgehen, den Charakter soweit eingeben, wie es geht, ihn in Json exportieren, im Json Export die Sonderfertigkeit hinzufügen (und die ausgegebenen Ap angepast), und danach die Json Datei wieder importiert. Das klappt auch gut, außer bei steigerbaren Sonderfertigkeiten (Belastungsgewöhnung, Kampfreflexe,  Finte usw.) Da bricht dann die Oberfläche.

======================================
Version 1.0.2

Import einer händisch angepassten Json Helden Datei
(Held erfüllt nicht die Voraussetzungen für steigerbare SF)
Aufrufen des Sonderfertigkieten Tabs

**Comment by Nafetsky** [comment]
OK, Fotos hochladen bekomme ich gerade nicht hin. Aber hier ist der StackTrace:
ERROR
TypeError: Cannot read property 'name' of undefined
    at ActivatableRemoveListItem.render (C:\Program Files\TDE5 Heroes\resources\app.asar\app\components\ActivatableRemoveListItem.js:51:45)
    at finishClassComponent (C:\Program Files\TDE5 Heroes\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:7873:31)
    at updateClassComponent (C:\Program Files\TDE5 Heroes\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:7850:12)
    at beginWork (C:\Program Files\TDE5 Heroes\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:8225:16)
    at performUnitOfWork (C:\Program Files\TDE5 Heroes\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:10224:16)
    at workLoop (C:\Program Files\TDE5 Heroes\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:10288:26)
    at HTMLUnknownElement.callCallback (C:\Program Files\TDE5 Heroes\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:542:14)
    at Object.invokeGuardedCallbackDev (C:\Program Files\TDE5 Heroes\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:581:16)
    at invokeGuardedCallback (C:\Program Files\TDE5 Heroes\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:438:27)
    at renderRoot (C:\Program Files\TDE5 Heroes\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:10366:7)
COMPONENT STACK

    in ActivatableRemoveListItem (created by ActivatableRemoveList)
    in ul (created by List)
    in List (created by ActivatableRemoveList)
    in div (created by Scroll)
    in div (created by Scrollbars)
    in div (created by Scrollbars)
    in Scrollbars (created by Scroll)
    in Scroll (created by ActivatableRemoveList)
    in ActivatableRemoveList (created by SpecialAbilities)
    in main (created by MainContent)
    in MainContent (created by SpecialAbilities)
    in div (created by Page)
    in Page (created by SpecialAbilities)
    in SpecialAbilities (created by Connect(SpecialAbilities))
    in Connect(SpecialAbilities) (created by Route)
    in Route (created by App)
    in section (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider

**Comment by Nafetsky** [comment]
{
	"clientVersion": "1.0.2",
	"phase": 2,
	"name": "Test",
	"ap": {
		"total": 900,
		"spent": 20
	},
	"el": "EL_1",
	"r": "R_1",
	"rv": "RV_1",
	"c": "C_1",
	"p": "P_0",
	"sex": "f",
	"pers": {},
	"attr": {
		"values": [["ATTR_1", 8, 1], ["ATTR_2", 8, 0], ["ATTR_3", 8, 0], ["ATTR_4", 8, 0], ["ATTR_5", 8, 0], ["ATTR_6", 8, 0], ["ATTR_7", 8, 0], ["ATTR_8", 8, 0]],
		"ae": 0,
		"kp": 0,
		"lp": 0,
		"permanentAE": {
			"lost": 0,
			"redeemed": 0
		},
		"permanentKP": {
			"lost": 0,
			"redeemed": 0
		}
	},
	"activatable": {
		"SA_29": [{
				"sid": 8,
				"tier": 4
			}
		],
		"SA_41": [{
				"tier": 1
			}
		]
	},
	"talents": {},
	"ct": {},
	"spells": {},
	"cantrips": [],
	"liturgies": {},
	"blessings": [],
	"belongings": {
		"items": {},
		"armorZones": {},
		"purse": {
			"d": "0",
			"h": "0",
			"k": "0",
			"s": "0"
		}
	},
	"rules": {
		"higherParadeValues": 0,
		"attributeValueLimit": false,
		"enableAllRuleBooks": true,
		"enableLanguageSpecializations": false,
		"enabledRuleBooks": []
	},
	"pets": {},
	"id": "H_1525621740878",
	"dateCreated": "2018-05-06T15:49:00.878Z",
	"dateModified": "2018-05-06T15:49:00.878Z"
}

**Comment by Elytherion** [comment]
Zunächst einmal: Bei den ausgegebenen AP muss ich dich leider enttäuschen, die werden nur gespeichert, damit in der Heldenliste ein Wert angezeigt wird, da die App aktuell (bin dabei, es zu ändern, ist nur sehr aufwändig) nicht in der Lage ist, die AP-Werte in der Heldenliste zu generieren. :P ;) Also das Editieren des Wertes hilft dir nicht beim Editieren in der App, da sie beim Arbeiten den Wert komplett on the fly berechnet.

Zum eigentlichen Problem: Ich kann mir vorstellen, dass der Fehler durch die nicht erfüllten Voraussetzungen hervorgerufen wird, kann es jedoch nicht mit Gewissheit sagen. Hast du probiert, ob es geht, wenn die Voraussetzungen erfüllt sind?

**Comment by Nafetsky** [comment]
OK, das mit den AP Werte ist schade. Aber verständlich.

Und ja, wenn ich die Eigenschaften an dem Import Char so anpasse, dass die Voraussetzungen erfüllt sind, geht alles glatt.
Also gemoddeter Char ist importiert
wechsel zu Sonderfertigkeiten -> Seite kaputt.
wechsel zu Eigenschaften
Eigenschaften steigern
wechsel zu Sonderfertigkeiten -> alles in ordnung

Also wie gesagt, ist ja auch keine normale Verwendung der Software. Aber leider ein Problem, das ich habe. Aber da würde ich wohl auch mit den Custome Sachen von #41 drüber kommen.

PS: Ansonsten ein sehr schönes Tool und jetzt gerade sehr bemerkenswerte Reaktionszeit.

**Comment by Elytherion** [comment]
Das mit dem dynamischen AP-Wert hat mehrere zusammenhängende Gründe: Wenn mal ein Wert falsch berechnet wurde, wurde dieser falsche Wert gespeichert und weiterverwendet. Manchmal hat man nicht bemerkt, dass die Werte falsch berechnet wurden, und in einigen Fällen ließen sich AP auch nicht 100%ig wiederherstellen - ich musste raten, was die Nutzer gemacht haben könnten, und dies in meine Funktion eingebaut, die nach einem Update die Charaktere auf die aktuelle Version anpasst und dabei eben hauptsächlich Bugs fixt. Ich konnte/kann aber nicht 100%ig gewährleisten, dass der Fix auch zufriedenstellend war. Gerade bei älteren Charakteren, die sehr viele Fähigkeiten besitzen, ist ein kaputter Charakter immer sehr schade, auch wenn ich das Problem vermutlich selber fixen könnte. Wenn mehrere Leute solche Probleme haben, kann das aber ganz schön Zeit fressen. Es kam auch mal vor, dass die App die AP zum Hinzufügen korrekt berechnete, die AP beim Entfernen jedoch nicht, man somit AP verlor/erhielt ohne Grund. Wenn nun mal ein Fehler in der AP-Berechnung ist, wird er beim nächsten Mal direkt behoben, ohne, dass ich irgendetwas verändern muss. Die Wahrscheinlichkeit für bleibende Schäden sinkt also extrem. (Das nur so als kleine Hintergrundinfo, falls es dich überhaupt interessiert xD :P)

Ah okay, alles klar. Ich würde es auf meine ToDo-Liste packen wollen, da Errors nie schön sind, auch bei nicht sachgemäßer Behandlung. Es wird aber sehr weit hinten auf der Liste stehen. ;)

Zu PS: Dankeschön! :) Zur Reaktionszeit: Mein Handy informiert mich eben sofort und ich lasse andere nur ungern warten. ;)

**Comment by Elytherion** [comment]
Eben getestet, jetzt wirft die App keinen Fehler mehr. 🎉 Allerdings solltest du beachten, dass eine Voraussetzung, die nicht erfüllt ist, umgekehrt wird von der Bedeutung. Im Fall der *Belastungsgewöhnung* kannst du dann in der App den Wert nicht höher als 12 steigern (und müsstest das dann auch manuell machen).
