### ISSUE TITLE
Angaben für Kletterseil und Seidenseil fehlerhaft

### ISSUE THREAD

**Issue by Arveldir** [Elytherion/tdeheroes#152]
Hi, ich muss sagen Optolyth gefällt mir richtig gut. Schöne übersichtliche Software.
Bei der Charaktererstellung habe ich jedoch festgestellt, dass das Template für Kletter- und Seidenseil fehlerhaft sind. Laut Rüstkammer sollte ein Kletterseil pro Schritt 0,3 S kosten (im Template 1 S). Für Seidenseile fehlen Angaben für Preis (1 S) und Gewicht (0,2 Stn).

V1.0.2 Win10

**Comment by Taugenix** [comment]
fixed

**Comment by Jordok** [comment]
Gibt hier widersprüchliche Informationen
Die Werte die hier notiert sind, sind korrekt wie sie in der ARÜI (Seite 30) stehen, allerdings im RGW (Seite 377) stehen die Werte wie sie vor dem fix waren.
Die RGW Werte sind interessanterweise ident mit den ARÜ Werten für ein Seidenseil, weshalb ich denke das die Änderung waren die Richtige Entscheidung.
