### ISSUE TITLE
no familiar/flying balm

### ISSUE THREAD

**Issue by seppestuyck** [Elytherion/tdeheroes#154]
As far as i can tell, you dont get the extra 10 ap reimbursed from the witch tradition.
Or am i missing something?

**Comment by Elytherion** [comment]
You can only see the effect on AP spent for special abilities and total AP spent. The difference is not included in AP at the actual special ability; it‘ll still show the standard AP cost. Does it have an effect on total AP spent or is there no effect at all?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seppestuyck** [comment]
After checking a few times more with new characters, im sure that the 10 point refund isnt being implemented.

**Comment by Elytherion** [comment]
Okay, thanks for checking, I‘ll take care of it! ;)
