### ISSUE TITLE
"Do you want to leave the page without saving? Y/N"

### ISSUE THREAD

**Issue by Kennin** [Elytherion/tdeheroes#158]
It would be nice if there were three options instead of two: yes/no/save

**Comment by Elytherion** [comment]
With the next update, this prompt will be removed, as you will be able to have multiple unsaved heroes at once. I will consider this for the prompt that will appear when closing the app with unsaved heroes, though.

**Comment by LLmichi1** [comment]
I would change the description to make things clearer: Yes/No/Save and close

**Comment by tfkraus** [comment]
Confirmed 
![image](https://user-images.githubusercontent.com/52836635/61152147-eea98b00-a4e7-11e9-9646-c7cad1475382.png)
