### ISSUE TITLE
Wrong traditions and aspects for liturgical chant "Verblassende Erinnerung"

### ISSUE THREAD

**Issue by Elytherion** [Elytherion/tdeheroes#171]
**Source:** https://www.orkenspalter.de/index.php?thread/23638-optolith-heldengenerator/&postID=851847#post851847

**Comment by Elytherion** [comment]
Additional source: https://www.orkenspalter.de/index.php?thread/23638-optolith-heldengenerator/&postID=864072#post864072

**Comment by Taugenix** [comment]
fixed
