### ISSUE TITLE
Add missing trade secrets from the Compendium I

### ISSUE THREAD

**Issue by Elytherion** [Elytherion/tdeheroes#180]
**Source:** https://www.orkenspalter.de/index.php?thread/23638-optolith-heldengenerator/&postID=859758#post859758

**Comment by Jordok** [comment]
Mehr infos notwendig, aus AKO1 sind alle drinnen. Alle anderen Regelwerke ab zu gleichen erscheint mir aktuell zu viel arbeit, wird bei der allgemeinen Kontrolle sinnvoller sein

**Comment by Elytherion** [comment]
Ich schau mir das bei Gelegenheit sonst nochmal an. Danke :3
