### ISSUE TITLE
Remove doubled trade secrets

### ISSUE THREAD

**Issue by Elytherion** [Elytherion/tdeheroes#183]
**Source:** https://www.orkenspalter.de/index.php?thread/23638-optolith-heldengenerator/&postID=860148#post860148

Also: "Elfenbogen" 3 AP and 5 AP => remove one of them?

**Comment by Jordok** [comment]
Viele doppelten haben unterschiedliche Kosten/Voraussetzungen.
Entfernte Berufsgeheimnisse, wie immer in Editable
ID:62 (Boltan)
ID:63 (Garadan)
ID: 65 (Kamelspiel)
