### ISSUE TITLE
Import crashes application

### ISSUE THREAD

**Issue by thutter** [Elytherion/tdeheroes#199]
I created a hero on a Windows 10 system and tried to import him to the application running on Ubuntu 18.04 system (64-bit). When I try to open the new character the application crashes with following error code:

```ERROR
TypeError: Cannot read property 'ic' of undefined
    at reduce (/home/toni/Downloads/989002-Optolyth_1.0.2_x64/Optolyth_1.0.2_x64/resources/app.asar/app/selectors/adventurePointsSelectors.js:19:63)
    at Array.reduce (<anonymous>)
    at exports.getAdventurePointsSpentForCombatTechniques.reselect_1.createSelector (/home/toni/Downloads/989002-Optolyth_1.0.2_x64/Optolyth_1.0.2_x64/resources/app.asar/app/selectors/adventurePointsSelectors.js:17:199)
    at /home/toni/Downloads/989002-Optolyth_1.0.2_x64/Optolyth_1.0.2_x64/resources/app.asar/node_modules/reselect/lib/index.js:76:25
    at /home/toni/Downloads/989002-Optolyth_1.0.2_x64/Optolyth_1.0.2_x64/resources/app.asar/node_modules/reselect/lib/index.js:36:25
    at /home/toni/Downloads/989002-Optolyth_1.0.2_x64/Optolyth_1.0.2_x64/resources/app.asar/node_modules/reselect/lib/index.js:90:33
    at /home/toni/Downloads/989002-Optolyth_1.0.2_x64/Optolyth_1.0.2_x64/resources/app.asar/node_modules/reselect/lib/index.js:36:25
    at /home/toni/Downloads/989002-Optolyth_1.0.2_x64/Optolyth_1.0.2_x64/resources/app.asar/node_modules/reselect/lib/index.js:86:37
    at /home/toni/Downloads/989002-Optolyth_1.0.2_x64/Optolyth_1.0.2_x64/resources/app.asar/node_modules/reselect/lib/index.js:36:25
    at /home/toni/Downloads/989002-Optolyth_1.0.2_x64/Optolyth_1.0.2_x64/resources/app.asar/node_modules/reselect/lib/index.js:86:37
COMPONENT STACK

    in Connect(NavigationBar) (created by App)
    in section (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider```

Optolyth version is 1.0.2 x64

**Comment by Elytherion** [comment]
Did you try to reimport it on Windows? => is this a Linux-only issue?

It would also be great if you could upload the hero's JSON file here.

Thanks! :)

**Comment by thutter** [comment]
It actually worked after I initially created a character and deleted it. After that the import worked completely fine 👍 
However here is the JSON if you still want to take a look at it ;)


```{"clientVersion":"1.0.2","phase":3,"name":"Perjin die Zunge","ap":{"total":1100,"spent":1100},"el":"EL_3","r":"R_1","rv":"RV_5","c":"C_6","p":"P_14","sex":"m","pers":{"placeofbirth":"Tuzak","age":"35","haircolor":5,"eyecolor":4,"size":"178","weight":"79","socialstatus":2,"cultureAreaKnowledge":"Tuzak"},"attr":{"values":[["ATTR_1",12,0],["ATTR_2",13,0],["ATTR_3",13,0],["ATTR_4",13,0],["ATTR_5",13,1],["ATTR_6",13,0],["ATTR_7",12,0],["ATTR_8",11,0]],"ae":0,"kp":0,"lp":0,"permanentAE":{"lost":0,"redeemed":0},"permanentKP":{"lost":0,"redeemed":0}},"activatable":{"ADV_13":[{"tier":1}],"ADV_18":[{}],"ADV_19":[{}],"ADV_22":[{}],"ADV_31":[{"tier":1}],"ADV_40":[{}],"ADV_51":[{}],"DISADV_16":[{}],"DISADV_33":[{"sid":1}],"SA_4":[{}],"SA_8":[{}],"SA_9":[{"sid":"TAL_13","sid2":1}],"SA_27":[{"sid":14},{"sid":9}],"SA_29":[{"sid":23,"tier":4},{"sid":8,"tier":3},{"sid":4,"tier":3},{"sid":17,"tier":1}]},"talents":{"TAL_4":4,"TAL_10":10,"TAL_11":4,"TAL_12":10,"TAL_13":10,"TAL_14":3,"TAL_15":3,"TAL_16":7,"TAL_18":7,"TAL_19":8,"TAL_20":10,"TAL_21":8,"TAL_22":10,"TAL_23":8,"TAL_27":7,"TAL_28":4,"TAL_29":3,"TAL_30":3,"TAL_31":8,"TAL_32":2,"TAL_34":4,"TAL_38":4,"TAL_39":3,"TAL_40":2,"TAL_46":5,"TAL_47":7,"TAL_48":6,"TAL_51":4,"TAL_54":8,"TAL_56":5,"TAL_57":8,"TAL_59":2},"ct":{"CT_3":12,"CT_4":12,"CT_9":10,"CT_11":10},"spells":{},"cantrips":[],"liturgies":{},"blessings":[],"belongings":{"items":{"ITEM_2":{"id":"ITEM_2","name":"Umhängetasche","gr":10,"amount":1,"where":"Rücken","price":8.5,"template":"ITEMTPL_214","isTemplateLocked":true},"ITEM_3":{"id":"ITEM_3","name":"Wasserschlauch","gr":10,"amount":1,"where":"Umhängetasche","price":5.5,"template":"ITEMTPL_216","isTemplateLocked":true},"ITEM_4":{"id":"ITEM_4","name":"Öllampe","gr":8,"amount":1,"where":"Gürtel","price":0.5,"template":"ITEMTPL_186","isTemplateLocked":true},"ITEM_5":{"id":"ITEM_5","name":"Zunderdose (Platz für 25 Portionen)","gr":8,"amount":1,"where":"Umhängetasche","price":1,"template":"ITEMTPL_192","isTemplateLocked":true},"ITEM_6":{"id":"ITEM_6","name":"Zunder, 25 Portionen","gr":8,"amount":1,"where":"Zunderdose","price":0.2,"template":"ITEMTPL_191","isTemplateLocked":true},"ITEM_7":{"id":"ITEM_7","name":"Puderdöschen","gr":10,"amount":1,"where":"Umhängetasche","price":6,"template":"ITEMTPL_207","isTemplateLocked":true},"ITEM_8":{"id":"ITEM_8","name":"Dietrichset (6 unterschiedliche Dietriche)","gr":12,"amount":1,"where":"Umhängetasche","price":0,"template":"ITEMTPL_409","isTemplateLocked":true},"ITEM_9":{"id":"ITEM_9","name":"Schleuder","gr":2,"amount":1,"where":"Umhängetasche","price":5,"template":"ITEMTPL_397","isTemplateLocked":true},"ITEM_11":{"id":"ITEM_11","name":"Kaffee, geröstet","gr":24,"amount":1,"where":"Umhängetasche","price":20,"template":"ITEMTPL_337","isTemplateLocked":true},"ITEM_12":{"id":"ITEM_12","name":"Nagelfeile","gr":24,"amount":1,"where":"Umhängetasche","price":20,"template":"ITEMTPL_342","isTemplateLocked":true},"ITEM_13":{"id":"ITEM_13","name":"Seife","gr":24,"amount":1,"where":"Umhängetasche","price":1,"template":"ITEMTPL_349","isTemplateLocked":true},"ITEM_14":{"id":"ITEM_14","name":"Spielkarten","gr":24,"amount":1,"where":"Umhängetasche","price":5,"template":"ITEMTPL_350","isTemplateLocked":true},"ITEM_15":{"id":"ITEM_15","name":"Taschentuch","gr":24,"amount":1,"where":"Umhängetasche","price":2,"template":"ITEMTPL_357","isTemplateLocked":true},"ITEM_16":{"id":"ITEM_16","name":"Würfel, sechsseitig","gr":24,"amount":1,"where":"Umhängetasche","price":0.5,"template":"ITEMTPL_360","isTemplateLocked":true},"ITEM_17":{"id":"ITEM_17","name":"Dolch","gr":1,"amount":1,"where":"Scheide","price":45,"template":"ITEMTPL_2","isTemplateLocked":true},"ITEM_18":{"id":"ITEM_18","name":"Stockdegen","gr":1,"amount":1,"where":"Körper","price":350,"template":"ITEMTPL_448","isTemplateLocked":true},"ITEM_19":{"id":"ITEM_19","name":"Steinchen","gr":3,"amount":4,"where":"Umhängetasche","price":0.1,"template":"ITEMTPL_398","isTemplateLocked":true},"ITEM_20":{"id":"ITEM_20","name":"Flöte","gr":23,"amount":1,"where":"Umhängetasche","price":2,"template":"ITEMTPL_319","isTemplateLocked":true},"ITEM_21":{"id":"ITEM_21","name":"Proviant für 1 Tag","gr":7,"amount":5,"where":"Umhängetasche","price":0.5,"template":"ITEMTPL_181","isTemplateLocked":true},"ITEM_23":{"id":"ITEM_23","name":"Schlafsack","gr":7,"amount":1,"where":"Umhängetasche","price":7,"template":"ITEMTPL_172","isTemplateLocked":true},"ITEM_24":{"id":"ITEM_24","name":"Tuchrüstung","gr":4,"amount":1,"where":"Körper","price":75,"template":"ITEMTPL_473","isTemplateLocked":true},"ITEM_25":{"id":"ITEM_25","name":"Fibel, Silber","gr":15,"amount":1,"where":"Haar","price":7.5,"template":"ITEMTPL_249","isTemplateLocked":true},"ITEM_26":{"id":"ITEM_26","name":"Halskette, Silber","gr":15,"amount":1,"where":"Hals","price":22,"template":"ITEMTPL_252","isTemplateLocked":true},"ITEM_27":{"id":"ITEM_27","name":"Ohrring, Silber","gr":15,"amount":1,"where":"Ohr","price":9.5,"template":"ITEMTPL_255","isTemplateLocked":true},"ITEM_28":{"id":"ITEM_28","name":"Ring, Silber","gr":15,"amount":2,"where":"Finger","price":7.5,"template":"ITEMTPL_258","isTemplateLocked":true},"ITEM_29":{"id":"ITEM_29","name":"Federkiel","gr":17,"amount":1,"where":"Umhängetasche","price":0.1,"template":"ITEMTPL_282","isTemplateLocked":true},"ITEM_30":{"id":"ITEM_30","name":"Tinte","gr":17,"amount":1,"where":"Umhängetasche","price":1,"template":"ITEMTPL_291","isTemplateLocked":true},"ITEM_31":{"id":"ITEM_31","name":"Pergament, 1 Blatt","gr":17,"amount":10,"where":"Umhängetasche","price":1,"template":"ITEMTPL_287","isTemplateLocked":true},"ITEM_32":{"id":"ITEM_32","name":"Verband, 10 Stück","gr":9,"amount":1,"where":"Umhängetasche","price":12.5,"template":"ITEMTPL_197","isTemplateLocked":true},"ITEM_33":{"id":"ITEM_33","name":"Dolchscheide","gr":5,"amount":1,"where":"Gürtel","price":5,"template":"ITEMTPL_89","isTemplateLocked":true}},"armorZones":{},"purse":{"d":"0","h":"23","k":"0","s":"90"}},"rules":{"higherParadeValues":0,"attributeValueLimit":false,"enableAllRuleBooks":true,"enableLanguageSpecializations":false,"enabledRuleBooks":[]},"pets":{},"id":"H_1534508725833","dateCreated":"2018-08-17T13:59:52.707Z","dateModified":"2018-08-17T13:59:52.707Z"}```
