### ISSUE TITLE
Advantage "Kleine Zauberauswahl" not available for "Intuitive Zauberer"

### ISSUE THREAD

**Issue by Elytherion** [Elytherion/tdeheroes#213]

**Comment by Jordok** [comment]
Sowohl der Nachteil "Kleine Zauberauswahl" als auch der Vorteil "Große Zauberauswahl" ist bei den Traditionen (Intuitiver Zauberer) und (Animisten) verfügbar. Bugmeldung noch aktuell?

**Comment by Elytherion** [comment]
Dann ist das wohl durch die Alpha gefixt.
