### ISSUE TITLE
"Scharfschütze II": Prerequisite should be INT 17 instead of INT 15

### ISSUE THREAD

**Issue by Elytherion** [Elytherion/tdeheroes#222]
**Source:** https://www.orkenspalter.de/index.php?thread/23638-optolith-heldengenerator/&postID=886319#post886319

**Comment by Jordok** [comment]
bereits behoben?

**Comment by Elytherion** [comment]
Nein. Es ging darum, dass die zweite Stufe auch INT 15 hatte, obwohl sie INT 17 haben müsste. Habs in der Haupttabelle beim Nachschlagen auch direkt mit behoben.
