### ISSUE TITLE
Avatar des Begleiters nur lokal verfügbar

### ISSUE THREAD

**Issue by supermopf** [Elytherion/tdeheroes#226]
Wenn ich ein Begleiter/Pet hinzufüge, wird dessen Avatar nur als Pfad im JSON gespeichert.
Sollte man den Helden nun Exportieren, ist der Avatar auf anderen Computern nicht verfügbar.
Wenn man im JSON den Pfad gegen base64 austauscht, funktioniert es.

Aufgetreten bei Version 1.0.2

**Comment by pupugit** [comment]
Cannot confirm in 1.1-Alpha18.
The Picture of a companion/pet for me isnt even saved inside the program:
1. Adding a pet with a picture
2. Then saving the character
3. exiting the program
4. reopening it again.
Picture of the pet/companion is gone.
