### ISSUE TITLE
Magier aus Perricum: calculating AE not working properly

### ISSUE THREAD

**Issue by Elytherion** [Elytherion/tdeheroes#238]
If SGC is higher than 12 the AE is on a lower value and does not increase anymore.

Original German source by NaKa on Discord:

> Betroffen ist der Gildenmagier aus Perricum, konkret die Kalkulation der AE. Leiteigenschaft ist KL, und bis zu einem Wert von 12 oder 13 funktioniert die Berechnung wie gehabt, aber bei höheren Werten wie 14 springt sie auf einmal zurück und das Tool errechnet nur noch 18 AE. Habe mal die eine oder andere Zauberprofession daraufhin angetestet, die haben dieses Problem nicht.

> Ich habe das Ganze jetzt nochmal rekonstruiert, und jetzt ein Ähnliches Phänomen auch dann, wenn ich sowohl bei KL als auch bei IN zwischen 12 und 13 springe.  Konkret: KL bis 12 = AE 31, ab 13 = AE 18. IN ab 12 = AE 30, darunter AE 18. Ist KL entsprechend hoch, steigt die AE aber auch bei höherer IN nicht weiter an. Andere Eigenschaften beeinflussen die AE nicht.

**Comment by Jordok** [comment]
Potentiell Veraltet, konnte den Fehler nicht reproduzieren
