### ISSUE TITLE
Belastung wird nicht einkalkuliert

### ISSUE THREAD

**Issue by Kallisto73** [Elytherion/tdeheroes#248]
Wenn ich eine Rüstung anlege, wird die Belastung nicht auf die Waffen angerechnet. Gleiches gilt für die Totalauslastung des Chars. Wenn diese kk*2+4 ist, sollte eine Belastungsstufe eingetragen werden, dann bei +8 zwei etc.
Mein char hat eine Rüstung mit BE 2, hat Belastungsgewöhnung I und MU 14 und 12 in Zweihandschertern.
Er sollte also eine AT von 12+2-2+1 haben, also 13. Er hat aber einfach nur 12+2, Rüstung wird vom Programm ignoriert.
Ich habe  dann mal den Charakter "beladen", selbes Ergebnis.

**Comment by Elytherion** [comment]
Das liegt daran, dass der Charaktergenerator aktuell noch nicht weiß, ob du die Rüstung trägst. Vielleicht hast du ja auch mal mehrere Rüstungen, dann wüsste er es erst recht nicht. Da getragene Rüstung ja auf andere Art Einfluss auf Gewicht/BE hat, wird es auch schwierig, diese zu berechnen und einfließen zu lassen. Daher wird aktuell auf Berechnungen abseits von AT/PA-Basis durch KtW + Einrechnung des AT/PA-Mods der jeweiligen Waffe verzichtet. #189 soll aber genau dieses Problem beheben. Da kann man dann festlegen, dass man eine bestimmte Waffe zusammen mit einer bestimmten Rüstung tragen möchte, und da er dann alle Einflüsse kennt, kann er BE usw. dann entsprechend berechnen. (Wenn du DSA4.1 gespielt hast, ist das dann in etwa wie die Item Sets in der Helden-Software.)
