### ISSUE TITLE
Hero Avatar not visible on Linux

### ISSUE THREAD

**Issue by Elytherion** [Elytherion/tdeheroes#254]
Only shows grey border, no actual image. Tested on Ubuntu. See Discord „Jim Knopf“.

**Comment by Elytherion** [comment]
Not working on Debian as well. Probably a problem with AppImage.

**Comment by LLmichi1** [comment]
Maybe a problem wirh the image path?
Paths in Linux are written slightly different compared to paths in Windows..

**Comment by Elytherion** [comment]
To show the images I need the file:// protocol, because it's what chromium needs to show the image. I thought, it looks the same for all OSs.

```ts
`file://${fileName.replace (/\\/g, "/")}`
```

This is basically what I do to convert the path from the OS to a `file://` path. I need the replace for windows, but am I missing sth I need to do to get it working on Linux?

**Comment by pupugit** [comment]
The error (which I was able to reproduce in version _1.0.3_) is fixed in _1.1.0-alpha18_.
Tested with Ubuntu 18.10

**Comment by Elytherion** [comment]
Thanks for double-checking!! :)
