### ISSUE TITLE
SF "Bindung des Bannschwerts" kostet keine AP. AP-Anzeige bleibt leer in der Auswahl. Die KT kann im Nachhinein nicht geändert werden.

### ISSUE THREAD

**Issue by LLmichi1** [Elytherion/tdeheroes#266]

**Comment by Elytherion** [comment]
Also Auswahlmöglichkeiten können im Nachhinein ja ohnehin nie geändert werden. Nur Stufen (zum "Aufleveln"). Ist aber mega seltsam, dass das nicht klappt. Es funktioniert *identisch* zu Schnellladen, und da klappt es!
