### ISSUE TITLE
Werte werden falsch berechnet

### ISSUE THREAD

**Issue by MorpheusLP** [Elytherion/tdeheroes#32]
AW sollte 9 sein (Verbessertes Ausweichen 1, GE 15), ist aber 8.
IN sollte 16 sein (MU 14 + GE 15)/2  ist aber 15
GS ist 8 sollte 9 sein. Habe ich einen Fehler in der Rechnung gemacht?
Ich habe die tulamidische Diebin (Regelwerk S. 71) nachgebaut und noch 91 AP übrig.
Version 48.1 glaub ich

**Comment by Elytherion** [comment]
*Verbessertes Ausweichen* wurde bislang nicht in die Berechnung einbezogen (frag nicht, warum ^^), ist es aber bereits für die nächste Version.
Selbiges gilt für *Flink*.
Kann es sein, dass die INI zwar im Attributtab einen Wert von 16 aufweist, nur auf dem Charakterbogen eben einen von 15?

**Comment by MorpheusLP** [comment]
Nein, die INI ist an allen Orten 15. Warum habe ich noch so viel AP übrig?

**Comment by Elytherion** [comment]
Okay. Hab den Fehler da jetzt auch eben gefunden.

Das mit den AP kann daran liegen, dass generell bei einigen (oder den meisten) Archetypen Rechenfehler drin sind. Ich würde empfehlen, das mit dem ausfällbaren Heldendokument ebenfalls auszutesten, falls du da dann auf die gleiche AP-Menge kommst, kannst du davon ausgehen, dass es ein Fehler seitens Ulisses ist. Falls nicht, werde ich mir das nochmal anschauen. (Sagen wir es so: Es wäre toll, wenn du das machen könntest, wenn nicht, werde ich das machen, kann dafür aber keinen genauen Zeitpunkt nennen, sodass sich die Behebung des Fehlers weiter nach hinten verschieben wird.)

Danke schon mal für alles! :)

**Comment by MorpheusLP** [comment]
Es ist kein Fehler von Ulisses. Ich hab gerade das PDF gemacht und es sind 0 AP übrig. Ich mache jetzt jeden Schritt einzeln und schau mal wo der Fehler sitzt.

**Comment by MorpheusLP** [comment]
Fehleraufzählung:
Bei der Erstellung (erster schritt) kann ich die Zeichen der Muttersprache auf zwei Arten kaufen. Die mit dem Kästchen wird nicht mitberechnet für die gesamtAP die ich für Sprachen und Schriften ausgeben darf(und ich muss somit mehr kaufen um weiterzukönnen). 
Nachdem ich die Erstellung des Programms im ersten Schritt beendete hatte ich noch 933 AP übrig. Eigentlich hätte ich nur noch laut Dokument 853 und nach meiner eigenen Rechnung (1100-28-218). 
Füchsisch regional ist noch nicht impementiert.
Im Programm ist der KTW bereits 12. Er sollte sich durch Streuner auf 10 befinden. Dafür ist die Armbrust/Wurfwaffen auf 6 statt eines davon auf 10.
Bei den Talenten ist mir nichts mehr aufgefallen.
Ich hoffe geholfen zu haben.

**Comment by MorpheusLP** [comment]
Warum kostet mich beim PDF die Diebin[218] 221 AP? sie sollte mich doch 218 kosten? (also nach Mhandastani[28] hatte ich -28 und nach Diebin[218] -249...

**Comment by Elytherion** [comment]
Zur Auswahl der Schrift der Muttersprache:
Dies ist kein Fehler, sondern beabsichtigt: Die Option, sich die Schrift der Muttersprache zu kaufen, ist eine Option der Kultur und nicht des Professionspaketes, weshalb diese Option auch unter "Kultur" gelistet ist. Für diese Zusatzoption *sollte* man dann auch die entsprechenden Kosten zusätzlich abgezogen bekommen. Möchte man das hingegen rein über das Professionspaket regeln, kann man das natürlich auch machen und ignoriert die Auswahl der Schrift der Muttersprache.

Das mit den AP ist seltsam. Das werde ich mit später noch anschauen...

Regionales Füchsisch ist eine Optionalregel. Optionalregeln habe ich - mit Ausnahme der unter Profil > Regeln genannten Optionalregeln - nicht implementiert. Steht aus dem Plan, hat bisher aber keine hohe Priorität.

Beim Eintragen der Werte habe ich da einen Fehler gemacht. Das könnte vielleicht auch das Problem mit den AP erklären. Werde das austesten, sobald ich die App wieder starten kann.

Bei ein paar Professionen und Professionsvarianten haben sich Rechenfehler eingeschlichen - so auch bei der Professionsvariante Dieb, dessen Kosten um 3 zu niedrig waren. Ich habe diese Kosten angepasst. (Hintergrund [hier](http://www.ulisses-us.com/forum/viewtopic.php?f=11&t=865) nachzulesen).

Du hast mir **sehr** viel geholfen, vielen vielen Dank dafür an dieser Stelle! Ich kann mir zwar nicht alle Fehler sofort genauer ansehen, werde es bei den restlichen aber tun, sobald ich es kann.

**Comment by Elytherion** [comment]
Für v0.49.0 wird die Profession jetzt korrekt eingefügt. Ich habe das auch separat über Eigene Profession getestet und für 221 AP bekommen beide die gleichen Boni. Ich konnte aber trotzdem nicht Belima mit 1100 AP erstellen - mir fehlen 24 AP. Sollte ich das Problem nicht bis einschließlich morgen behoben haben, werde ich das Update ohne Bugfix hochladen - denn alle anderen Bugs sind gefixt.

**Comment by Elytherion** [comment]
Es funktioniert nun alles wie es soll.
