### ISSUE TITLE
Add Subtext for Profession "GraumagierIn"

### ISSUE THREAD

**Issue by Stemw3** [Elytherion/tdeheroes#34]
There is currently no subtext for the "GraumagierIn"-Professions. This leads to 9 professions which have the same name but different AP-Values. 

Version: 0.48.1

![uwebhqe](https://user-images.githubusercontent.com/9552107/28540852-1a13247a-70b7-11e7-95cd-1bd72326bfec.png)

**Comment by Stemw3** [comment]
I think this addition to my issue is unnecessary but just for the completion: This is not limited to the "GraumagierIn", but most of the Mage-Type Professions do lack a subtext for the academy where the students get taught.

**Comment by Elytherion** [comment]
> [...] most of the Mage-Type Professions [...]

**Most** of them or **all** of them?

**Comment by Stemw3** [comment]
Most of them. For example, the "SchwarmagierIn" has 1 out of 4 with a subtext. WeissmagierIn also only has 1 with subtext.
![wctmkib](https://user-images.githubusercontent.com/9552107/28541488-76fece94-70b9-11e7-8c81-863af3cc3538.png)

**Comment by Stemw3** [comment]
And to make the list full: Gildenlose MagierIn has 3 out of 4 with subtext.
![bopknft](https://user-images.githubusercontent.com/9552107/28541548-b338f86c-70b9-11e7-9276-b12e4dc2d499.png)

**Comment by Elytherion** [comment]
Okay, thank you! :)

**Comment by Elytherion** [comment]
Please check this issue with the upcoming 0.49.0 update - as it is working as intended with my current local version.

**Comment by Stemw3** [comment]
It works.  Although it's kinda irritating that the order of the is changing randomly when you select the different types.

Example:
Marked: "Schüler des Alrik Dagabor".
"Schüler des Magister Dagabor" is 2nd from bottom.
![1](https://user-images.githubusercontent.com/9552107/29252576-a0824186-806a-11e7-8b7b-3c598b06eb0e.png)

When I then change the mark to: "Seminar der Elfischen Verständigung und natürlichen Heilung zu Donnerbach".
"Schüler des Magister Dagabor" is 2nd from top.
The "Schüler der Khelbara Ay Babury" went to the bottom".
The now marked one went one place up.
![2](https://user-images.githubusercontent.com/9552107/29252706-3bb54a08-806c-11e7-9594-5c2eb2432a7a.png)

If i can guess the issue I'd say, that the sort-algorithm does randomize these professions because they all have the same name (and thus the same sort-key)?
(Maybe I should make a new issue for that but... idk :x )

**Comment by Elytherion** [comment]
I just forgot to readd sorting by subname after sorting by name ... fixed! ;)
