### ISSUE TITLE
App freezes after clicking on the "Besitz" Tab

### ISSUE THREAD

**Issue by MasterFee** [Elytherion/tdeheroes#36]
Version 0.48.2 (macOS)

My steps to the error: Create new Character -> finish creation -> add equipment (might be a specific one, but I'm not sure which one it could be) -> save -> clicking on the tab "Besitz" freezes the main window

Error Description:
Main window (everything beneath the tabs) freezes to the current selected one (all BUT "Besitz" or "Heldenbogen" work just fine) and can only be reverted by a restart.

The exception the console gives when clicking on the tab "Besitz" is as follows:
/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOM.js:73 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:46 Uncaught TypeError: Cannot read property 'localeCompare' of undefined
    at exports.sortByGroupName (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/app/utils/FilterSortUtils.js:46:15)
    at Array.sort (native)
    at sort (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/app/utils/FilterSortUtils.js:100:17)
    at Object.filterAndSort (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/app/utils/FilterSortUtils.js:126:12)
    at Equipment.render (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/app/views/belongings/Equipment.js:61:40)
    at /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:795:21
    at measureLifeCyclePerf (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:794:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-03D4945F6738/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
exports.sortByGroupName @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:46
sort @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:100
filterAndSort @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:126
render @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:61
(anonymous) @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:795
measureLifeCyclePerf @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:75
_renderValidatedComponentWithoutOwnerOrContext @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:794
_renderValidatedComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:821
performInitialMount @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:361
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:257
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:45
mountChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:236
_createInitialChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:703
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:522
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:45
performInitialMount @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:370
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:257
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:45
_updateRenderedComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:764
_performComponentUpdate @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:723
updateComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:644
receiveComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:546
receiveComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:124
updateChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:109
_reconcilerUpdateChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:206
_updateChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:310
updateChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:297
_updateDOMChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:942
updateComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:760
receiveComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:722
receiveComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:124
_updateRenderedComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:753
_performComponentUpdate @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:723
updateComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:644
performUpdateIfNecessary @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:560
performUpdateIfNecessary @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:156
runBatchedUpdates @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:150
perform @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:143
perform @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:143
perform @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:89
flushBatchedUpdates @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:172
closeAll @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:209
perform @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:156
batchedUpdates @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:62
batchedUpdates @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:97
dispatchEvent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/E2169AA4-30D6-4EE2-923F-0…:147

The exception after clicking on the "Heldenbogen" button:
/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOM.js:73 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:46 Uncaught TypeError: Cannot read property 'localeCompare' of undefined
    at exports.sortByGroupName (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/app/utils/FilterSortUtils.js:46:15)
    at Array.sort (native)
    at Object.sort (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/app/utils/FilterSortUtils.js:100:17)
    at BelongingsSheet (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/app/views/profile/BelongingsSheet.js:37:37)
    at /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:305:16
    at measureLifeCyclePerf (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:304:14)
    at ReactCompositeComponentWrapper._constructComponent (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:279:21)
    at ReactCompositeComponentWrapper.mountComponent (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeComponent.js:187:21)
    at Object.mountComponent (/private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C6BD1D9C1A7D/d/tdeheroes.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:45:35)
exports.sortByGroupName @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:46
sort @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:100
BelongingsSheet @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:37
(anonymous) @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:305
measureLifeCyclePerf @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:75
_constructComponentWithoutOwner @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:304
_constructComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:279
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:187
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:45
mountChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:236
_createInitialChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:703
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:522
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:45
mountChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:236
_createInitialChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:703
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:522
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:45
mountChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:236
_createInitialChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:703
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:522
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:45
performInitialMount @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:370
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:257
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:45
performInitialMount @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:370
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:257
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:45
mountChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:236
_createInitialChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:703
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:522
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:45
performInitialMount @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:370
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:257
mountComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:45
updateChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:121
_reconcilerUpdateChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:206
_updateChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:310
updateChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:297
_updateDOMChildren @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:942
updateComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:760
receiveComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:722
receiveComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:124
_updateRenderedComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:753
_performComponentUpdate @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:723
updateComponent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:644
performUpdateIfNecessary @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:560
performUpdateIfNecessary @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:156
runBatchedUpdates @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:150
perform @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:143
perform @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:143
perform @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:89
flushBatchedUpdates @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:172
closeAll @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:209
perform @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:156
batchedUpdates @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:62
batchedUpdates @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:97
dispatchEvent @ /private/var/folders/yq/27jj750d0s3d7v5fn6jsn0640000gn/T/AppTranslocation/05068644-B176-4A07-839B-C…:147
[Violation] 'click' handler took 263ms

**Comment by MasterFee** [comment]
Didn't appeared in other report, for me at least. Going to check in new version once released, thanks for quick response!

**Comment by Elytherion** [comment]
I found it on my own and it was privately reported, too; I am sorry about not mentioning this one (sadly, sometimes I still forget to publish bugs I found on my own/reported privately)! But as I said, I am not sure whether it is the same bug or not.

**Comment by MasterFee** [comment]
Like I said, I'm going to check if it was fixed in the latest release or not and then report back to you.

**Comment by Elytherion** [comment]
As there were no further error reports and I am not experiencing this issue I will close it for now. Feel free to reopen if you still have problems.
