### ISSUE TITLE
Abilities for (dis)advantages are not choosable.

### ISSUE THREAD

**Issue by Stemw3** [Elytherion/tdeheroes#37]
English tl:dr: You can't choose an ability for advantages or disadvantages when those require one.
(I'll stick to german for the long explanation because it's far easier to report in my main language (obviously))

Beim Versuch meinen Charakter zu erstellen bin ich zu dem Problem gekommen, dass die Vorteile "Begabung", "Herausragende Fertigkeit" und "Herausragende Kampftechnik", ebenso wie der Nachteil "Unbegabt" nicht die Auswahl eines entsprchenden Fertigkeit zulassen. Da aber anscheinend eine entsprechende Eingabe nötig ist, um den Vorteil/Nachteil hinzuzufügen, sind diese nicht hinzufügbar.

Bsp:
![1](https://user-images.githubusercontent.com/9552107/29252843-ed117982-806e-11e7-96a6-ec17374b7e89.png)

**Comment by Elytherion** [comment]
Fixed for next version!
