### ISSUE TITLE
Astral points and magic page missing for "intuitiver Zauberer"

### ISSUE THREAD

**Issue by maufl** [Elytherion/tdeheroes#45]
Hi, I'm using the latest version 0.49.1.
I've created an "intuitiver Zauberer" and was able to select "Zaubertricks". However, the character sheet does not include a page that lists the "Zaubertricks". Furthermore, my character has no astral energy.

**Comment by maufl** [comment]
Thanks for the fast response. Is there any possibility to help with coding?

**Comment by Elytherion** [comment]
There is, yes. Could you send me an e-mail so I can provide some details (I dont know how to send an e-mail to a user without a public e-mail :O )

**Comment by Elytherion** [comment]
Just invited you as a collaborator so you can check out the source code. Please check out the CONTRIBUTING.md (in the code repo); I will create issues for stuff that needs to be done ;)

**Comment by maufl** [comment]
Thanks :) I sent you an email and will try to get familiar with the code base later today.
