### ISSUE TITLE
Adding AP adds it to "used" instead of "available".

### ISSUE THREAD

**Issue by Stemw3** [Elytherion/tdeheroes#46]
tl:dr.: If you add AP they get added to "ap used" instead of "ap overall".

Beispiel:
Voher:
![1](https://user-images.githubusercontent.com/9552107/29429516-42411dde-8391-11e7-9e07-218f7af484ed.png)

85 AP hinzufügen...
![2](https://user-images.githubusercontent.com/9552107/29429585-7eb3730c-8391-11e7-9bb5-31a297608036.png)

Nach dem hinzufügen von 85 AP:
![3](https://user-images.githubusercontent.com/9552107/29429603-8eea16fe-8391-11e7-93ea-744338b3e0e3.png)

**Comment by Elytherion** [comment]
Indeed. Fixed!
