### ISSUE TITLE
Language change crashes character creation

### ISSUE THREAD

**Issue by MorpheusLP** [Elytherion/tdeheroes#52]
After using my program in german for a while I tried to make an english character. After changing the language and restarting the client I clicked "create". I selected my stats (irrelevant. All combinations lead to crash) and pressed "start" the program crashed.
![fehler](https://user-images.githubusercontent.com/30218054/29708864-91fadd3e-898a-11e7-9eb5-ea904567ac78.PNG)

**Comment by MorpheusLP** [comment]
A friend of mine has the same problem but without using german once.

**Comment by Elytherion** [comment]
I will upload 0.49.2 this evening.
