### ISSUE TITLE
Bug Rückgängigtaste bei Firnelfen

### ISSUE THREAD

**Issue by Condance** [Elytherion/tdeheroes#53]
![bug](https://user-images.githubusercontent.com/31402718/29765301-f7610ec6-8bda-11e7-8a5f-488299ed7653.JPG)

Diese Meldung erscheint, wenn ich Firnelfen als Klasse und Spezies ausgewählt habe und bei der Professionsauswahl rückgängig machen drücke.

**Comment by Elytherion** [comment]
Kann es sein, dass das immer passiert, wenn man seine Kulturauswahl rückgängig macht und im Professionstab ist?
