### ISSUE TITLE
Bug Kampftalentwertberechnung

### ISSUE THREAD

**Issue by Condance** [Elytherion/tdeheroes#54]
Bei Kampftalenten der Leiteigenschaften GE und KK, sowie GE/KK berechnet er den Bonus auf AT und PA mit MU statt der jeweiligen Leiteigenschaft.

**Comment by Elytherion** [comment]
Wo ist das denn der Fall? Generell? Nur auf dem Heldenbogen? Ich bin gerade nochmal jeden Testcharakter durchgegangen und jeder funktioniert so wie er soll, sowohl im Kampftechniktab als auch auf dem Kampfbogen. Das ist extrem seltsam ...

Ein Screenshot als Ergänzung wäre noch super!

Danke! :)

**Comment by Elytherion** [comment]
Wie gesagt und wie du auch hier ![screenshot 93](https://user-images.githubusercontent.com/11094577/29998996-e7e3924a-9038-11e7-87ac-c72003ee70db.png) bei MU 14 und KK 10 sehen kannst, funktioniert die Berechnung so wie sie soll. Und ich verwende 0.49.2 bzw. 0.49.3. Ich habe auch immer noch keine Stelle gefunden, wo es nicht so ist wie es sein soll.
Ich bräuchte auf jeden Fall noch die oben genannten Details und am besten auch den Screenshot von dir, damit ich mich damit nochmal sinnvoll auseinandersetzen kann! :)

**Comment by Condance** [comment]
Oo naja eben nicht, dein Screenshot beweist es doch sogar. Bei KK10 Müsste der AT Wert bei 6 sein und nicht 8, da ja nicht MU sondern KK für lanzen ausschlaggebend ist.

**Comment by Elytherion** [comment]
Wenn du da Probleme hast und ich nicht würde ich trotzdem gerne versuchen, dir in diesem Punkt irgendwie zu helfen, indem ich den Bug behebe. Wie gesagt, dafür bräuchte ich die oben genannten Infos bzw. Screenshots.

Was die Lanzen-AT und -PA angeht: Im Regelwerk hat die Kampftechnik Lanzen einen PA-Wert, ergo muss ihr AT mit MU und ihr PA mit ihrer Leiteigenschaft, also KK, berechnet werden ... oder nicht?

**Comment by Condance** [comment]
Ach ja, hab das jetzt nochmal nachgelesen, du hast vollkommen recht. Ich bin davon ausgegangen, dass die Leiteigenschaft sich auf AT und PA auswirkt. Dann bitte ich vielmals und Entschuldigung, für diesen Aufstand meiner Seits. Also ist es wie du schon gesagt hast, kein Fehler da, alles korrekt.

**Comment by Elytherion** [comment]
Alles klar, kein Problem! :)
