### ISSUE TITLE
Obergrenze nicht dekrementiert

### ISSUE THREAD

**Issue by MorpheusLP** [Elytherion/tdeheroes#59]
Wann immer ein Vorteil aktiviert wieder und deaktiviert oder verringert (Adel II wird zu Adel I= -5 APunkte) wird, steigt der Zähler für die 80 Ap Maximum um den eigentlich entfernten Wert. AP werden korrekt zurückgegeben. v1.7.3
Beispiel: Anfang: 0 Punkte, Adel II gekauft: 10/80, Adel II zu Adel I geändert: 15/80, Adel I gelöscht: 20/80

**Comment by Elytherion** [comment]
Dieser Bug wurde schon in #56 gemeldet und behoben!
