### ISSUE TITLE
Application crashes by typing '*' in search-field

### ISSUE THREAD

**Issue by ScullyBlue** [Elytherion/tdeheroes#68]
When I typed the character '*' in the search-field, I get a JS-Exeption:
SyntaxError: Invalid regular expression: /*/: Nothing to repeat

**Comment by Elytherion** [comment]
That's strange. Actually, I'm not using regular expressions for searching. Did it occur in all search fields?

**Comment by Elytherion** [comment]
Okay, never mind, did not know that the method I used for comparing strings converts the string given by the search field to a regular expression... Fixed for next version. Thanks! :)

**Comment by ScullyBlue** [comment]
Yes, it occures in all search fields.
But it occures only, if you type the '*' at FIRST Character. Follows the '*' other characters, doesnt affect the result and it doesnt crashes.

Btw I saw, that the searchpattern matches also, if its part of result, so the '*' is not necessery, but the programm shouldnt crash, if someone - like me - typed it out of habit.


Thanks for fixing!
