### ISSUE TITLE
Adding Advantages/Disadvantages after Creation

### ISSUE THREAD

**Issue by Stemw3** [Elytherion/tdeheroes#73]
You should be able to add Advantages and Disadvantages after the creation of your character (and then without the 80AP/-80AP maximum.)

Derzeit gibt es keine Möglichkeit nach der Erstellung des Helden zusätzliche Vorteile/Nachteile hinzuzufügen. Obwohl bei den Regeln steht, dass in der Regel keine Vorteile/Nachteile im Laufe des Heldenleben hinzukommen, gibt es doch entsprechende Ausnahmen, die auch in den Regeln niedergeschrieben sind. (Beispiel: Glück III, welcher nur nach der Heldenerstellung erworben werden kann, weil diese pro Stufe 30AP kosten. (Regelwerk S.165))

**Comment by Elytherion** [comment]
This is covered by #40 and [this poll](https://www.orkenspalter.de/index.php?thread/23638-dsa5-heldentool-alpha/&postID=783083#post783083).
