### ISSUE TITLE
Random weight produces negative numbers

### ISSUE THREAD

**Issue by Tzuyoshi** [Elytherion/tdeheroes#80]
As the title says. the random button for the weight, at the character creation, produces negative values. 
Specifically, when the height is really low in the range of 0 to 90. 
That could either happen when the user wants to input a meter-value, such as "1,75" or wants to play a kid(which isn't covered by the core rules, I know the formula).
I would suggest to limit the height field to only numbers, so the user won't input a meter-value instead of a "Halbfinger"/cm value.

**Comment by Elytherion** [comment]
The input fields for age, size and weight will now have red borders if the contained values are invalid numbers (empty is ignored). If the size is a floating number the app will multiply the value by 100 when generating the weight value and will insert the cm value. Thanks!
