### ISSUE TITLE
Missing Special Abillity Entrys

### ISSUE THREAD

**Issue by Tzuyoshi** [Elytherion/tdeheroes#86]
In V0.50.0
There are most special abillitys not available, I only checked the Core Rules.
Here is the list of the German names:

-- Allg. Sonderfertigkeiten - Missing

- Analytiker
- Anführer
- Dokumentenfälscher
- Fächersprache
- Fallen entschärfen
- Falschspielen
- Fertigkeitsspezialisierung
- Fischer
- Füchsisch
- Gildenrecht
- Glasbläserei
- Hehlerei
- Heraldik
- Instrumente bauen
- Jäger
- Kartographie
- Lippenlesen
- Rosstäuscher	
- Sammler
- Schmerzen unterdrücken
- Schnapsbrennerei
- Schriftstellerei
- Tierstimmen imitieren
- Töpferei
- Wettervorhersage
- Zahlenmystik

-- Kampfsonderfertigkeiten - Missing
- Aufmerksamkeit
- Belastungsgewöhnung
- Beidhänder Kampf
- Berittener Kampf
- Berittener Schütze
- Einhändiger Kampf
- Entwaffnen
- Feindgespür
- Finte
- Hammerschlag
- Kampfreflexe
- Klingenfänger
- Kreuzbock
- Lanzenangriff
- Präziser Schuss / Wurf
- Präziser Stich	
- Riposte	
- Rundumschlag
- Schildspalter
- Schnellladen
- Schnellziehen
- Sturmangriff
- Todesstoß
- Verbessertes Ausweichen
- Verteidigungshaltung
- Vorstoß
- Wurf
- Zu Fall bringen

And at the end, I also noticed that the fate point abillity "Wachsamkeit verbessern" has an entry called only "Wachsamkeit".

**Comment by Elytherion** [comment]
At least most of them are working for me (couldnt check all right now). Did you check the listed prerequisites? You need to meet them.

Concerning the last one: http://www.ulisses-regelwiki.de/index.php/SF_Wachsamkeit.html

**Comment by Tzuyoshi** [comment]
oh, OK my bad, didn't met the prerequisites. Just tried everything with a dummy cahr, because a hero of mine couldn't learn some. As it turns out, he could not learn them because of the prerequisites... There are some times, where the problem sits behind the keyboard.

Regarding the Wachsamkeit, in the table in the core rules its called "Wachsamkeit verbessern", so a typo in the book, rather than the programm...

**Comment by Elytherion** [comment]
;)

Probably copy-&-paste issue.
