### ISSUE TITLE
Adding shortcuts

### ISSUE THREAD

**Issue by Onyxmoon** [Elytherion/tdeheroes#95]
Applies to all platforms

Add shortcuts to match known UX flows.

For example: 

- CTRL/⌘ + S - for saving
- ⌘ + Q - for closing (macOS specific)
- CTRL/⌘ + Z - for undoing
- CTRL+ Y/⌘ + ⇧ + Z  - for redo

**Comment by Elytherion** [comment]
Implemented above shortcuts and the following:

* Ctrl/Command + O: Open settings
* Ctrl/Command + W: Back (go to herolist when in hero view; same as clicking on the back button in the upper left corner)
